name: FreeCloud 自动续费

on:
  schedule:
    - cron: '30 2 * * *'  # 每天北京时间 10:30（UTC+8）运行
  workflow_dispatch:       # 可手动触发

jobs:
  renew:
    runs-on: ubuntu-latest

    env:
      FC_USERNAME: ${{ secrets.FC_USERNAME }}
      FC_PASSWORD: ${{ secrets.FC_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run renewal script
        run: python renew.py
